INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Spec Ops', 'Browning');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Recon Force', 'Browning');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Range Ops', 'Browning');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Strike Force', 'Browning');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Trophy Cam HD Max', 'Bushnell');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Trophy Cam HD', 'Bushnell');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Code Black 3G', 'Covert');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Black 60', 'Covert');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Red 40', 'Covert');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('MP6', 'Covert');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('MP-E5', 'Covert');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('G22-T70IR', 'Hunten');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('G35-50IR', 'Hunten');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('G35-40IR', 'Hunten');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('G35-20IR', 'Hunten');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('RCX-2', 'Leupold');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('RCX-1', 'Leupold');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Panoramic 150i', 'Moultrie');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('M-990i', 'Moultrie');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('M-880', 'Moultrie');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('A-5', 'Moultrie');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('M-880i', 'Moultrie');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('M-550', 'Moultrie');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('M-880C', 'Moultrie');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Pro', 'Plotwatcher');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Truth Cam EL Blackout', 'Primos');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Truth Cam Ultra 46', 'Primos');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Truth Cam Ultra 35', 'Primos');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('HC600', 'Reconyx');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('HC500', 'Reconyx');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('SC950 Cellular', 'Reconyx');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('SG565', 'Scoutguard');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('SG560C', 'Scoutguard');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Tiny W2', 'Spypoint');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Tiny W3', 'Spypoint');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('BF-10HD', 'Spypoint');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Live 3G', 'Spypoint');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('BF-8', 'Spypoint');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('I-6', 'Spypoint');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('G42NG', 'Stealth Cam');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('G30', 'Stealth Cam');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('UM562', 'Uway');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('MB500', 'Uway');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('U150', 'Uway');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('VH200', 'Uway');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Panda Wireless', 'Uway');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Pulse 10', 'Wildgame Innovations');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Pulse 10D', 'Wildgame Innovations');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Red 6', 'Wildgame Innovations');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('TK40 No-Glow', 'Wildview');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('TK30', 'Wildview');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('X8IR No-Glow', 'Wildview');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Raptor', 'Pixcontroller');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1149', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1156', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1163', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1170', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1187', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1194', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1224', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1231', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1248', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1255', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1279', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1286', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('1309', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('C1', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('C123', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('C2', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('C23', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('C3', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('E2', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('E3', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('F2', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('F2-20', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('F3-20', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Kryptek 1234', 'Cuddeback');
INSERT INTO Wild_ID.camera_model(name, maker) VALUES('Mossy Oak F2-C', 'Cuddeback');
