
CREATE TABLE  IF NOT EXISTS `deployment` (
  `deployment_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(250) DEFAULT NULL,
  `event_id` int(11) NOT NULL,
  `camera_trap_id` int(11) NOT NULL,
  `camera_id` int(11) NOT NULL,
  `start_time` timestamp,
  `end_time` timestamp,
  `bait_type_id` int(11) NOT NULL,
  `feature_type_id` int(11) DEFAULT NULL,
  `quiet_period_setting` varchar(128) DEFAULT NULL,
  `set_person_id` int(11) DEFAULT NULL,
  `pick_person_id` int(11) DEFAULT NULL,
  `failure_detail` text,
  `restrction_on_access` varchar(250) DEFAULT NULL,
  `bait_detail` varchar(250) DEFAULT NULL,
  `feature_type_detail` varchar(250) DEFAULT NULL,
  `failure_type_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`deployment_id`),
  KEY `fk_deployment_event` (`event_id`),
  KEY `fk_deployment_camera_trap` (`camera_trap_id`),
  KEY `fk_deployment_camera` (`camera_id`),
  KEY `fk_deployment_bait_type` (`bait_type_id`),
  KEY `fk_deployment_feature_type` (`feature_type_id`),
  KEY `fk_deployment_set_person` (`set_person_id`),
  KEY `fk_deployment_pick_person` (`pick_person_id`),
  KEY `fk_deployment_failure_type_idx` (`failure_type_id`),
  CONSTRAINT `fk_deployment_bait_type` FOREIGN KEY (`bait_type_id`) REFERENCES `bait_type` (`bait_type_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_deployment_camera` FOREIGN KEY (`camera_id`) REFERENCES `camera` (`camera_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_deployment_camera_trap` FOREIGN KEY (`camera_trap_id`) REFERENCES `camera_trap` (`camera_trap_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_deployment_event` FOREIGN KEY (`event_id`) REFERENCES `event` (`event_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_deployment_failure_type` FOREIGN KEY (`failure_type_id`) REFERENCES `failure_type` (`failure_type_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_deployment_feature_type` FOREIGN KEY (`feature_type_id`) REFERENCES `feature_type` (`feature_type_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_deployment_pick_person` FOREIGN KEY (`pick_person_id`) REFERENCES `person` (`person_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_deployment_set_person` FOREIGN KEY (`set_person_id`) REFERENCES `person` (`person_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
