INSERT INTO Wild_ID.continent(continent_id, name) VALUES(1,'Unknown');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Afghanistan','AFG');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Albania','ALB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Algeria','DZA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'American Samoa','ASM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Andorra','AND');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Angola','AGO');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Anguilla','AIA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Antarctica','ATA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Antigua and Barbuda','ATG');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Argentina','ARG');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Armenia','ARM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Aruba','ABW');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Australia','AUS');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Austria','AUT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Azerbaijan','AZE');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Bahamas','BHS');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Bahrain','BHR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Bangladesh','BGD');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Barbados','BRB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Belarus','BLR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Belgium','BEL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Belize','BLZ');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Benin','BEN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Bermuda','BMU');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Bhutan','BTN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Bolivia, Plurinational State of','BOL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Bonaire, Sint Eustatius and Saba','BES');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Bosnia and Herzegovina','BIH');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Botswana','BWA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Bouvet Island','BVT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Brazil','BRA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'British Indian Ocean Territory','IOT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Brunei Darussalam','BRN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Bulgaria','BGR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Burkina Faso','BFA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Burundi','BDI');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Cambodia','KHM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Cameroon','CMR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Canada','CAN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Cape Verde','CPV');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Cayman Islands','CYM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Central African Republic','CAF');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Chad','TCD');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Chile','CHL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'China','CHN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Christmas Island','CXR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Cocos (Keeling) Islands','CCK');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Colombia','COL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Comoros','COM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Congo','COG');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Congo, the Democratic Republic of the','COD');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Cook Islands','COK');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Costa Rica','CRI');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Croatia','HRV');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Cuba','CUB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Curaçao','CUW');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Cyprus','CYP');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Czech Republic','CZE');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Côte D''Ivoire','CIV');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Denmark','DNK');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Djibouti','DJI');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Dominica','DMA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Dominican Republic','DOM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Ecuador','ECU');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Egypt','EGY');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'El Salvador','SLV');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Equatorial Guinea','GNQ');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Eritrea','ERI');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Estonia','EST');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Ethiopia','ETH');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Falkland Islands (Malvinas)','FLK');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Faroe Islands','FRO');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Fiji','FJI');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Finland','FIN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'France','FRA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'French Guiana','GUF');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'French Polynesia','PYF');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'French Southern Territories','ATF');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Gabon','GAB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Gambia','GMB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Georgia','GEO');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Germany','DEU');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Ghana','GHA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Gibraltar','GIB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Greece','GRC');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Greenland','GRL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Grenada','GRD');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Guadeloupe','GLP');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Guam','GUM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Guatemala','GTM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Guernsey','GGY');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Guinea','GIN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Guinea-Bissau','GNB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Guyana','GUY');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Haiti','HTI');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Heard Island and McDonald Islands','HMD');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Holy See (Vatican City State)','VAT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Honduras','HND');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Hong Kong','HKG');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Hungary','HUN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Iceland','ISL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'India','IND');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Indonesia','IDN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Iran, Islamic Republic of','IRN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Iraq','IRQ');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Ireland','IRL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Isle of Man','IMN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Israel','ISR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Italy','ITA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Jamaica','JAM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Japan','JPN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Jersey','JEY');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Jordan','JOR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Kazakhstan','KAZ');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Kenya','KEN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Kiribati','KIR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Korea, Democratic People''s Republic of','PRK');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Korea, Republic of','KOR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Kosovo, Republic of','XKX');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Kuwait','KWT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Kyrgyzstan','KGZ');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Lao People''s Democratic Republic','LAO');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Latvia','LVA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Lebanon','LBN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Lesotho','LSO');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Liberia','LBR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Libya','LBY');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Liechtenstein','LIE');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Lithuania','LTU');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Luxembourg','LUX');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Macao','MAC');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Macedonia, the Former Yugoslav Republic of','MKD');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Madagascar','MDG');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Malawi','MWI');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Malaysia','MYS');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Maldives','MDV');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Mali','MLI');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Malta','MLT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Marshall Islands','MHL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Martinique','MTQ');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Mauritania','MRT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Mauritius','MUS');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Mayotte','MYT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Mexico','MEX');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Micronesia, Federated States of','FSM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Moldova, Republic of','MDA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Monaco','MCO');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Mongolia','MNG');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Montenegro','MNE');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Montserrat','MSR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Morocco','MAR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Mozambique','MOZ');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Myanmar','MMR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Namibia','NAM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Nauru','NRU');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Nepal','NPL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Netherlands','NLD');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'New Caledonia','NCL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'New Zealand','NZL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Nicaragua','NIC');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Niger','NER');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Nigeria','NGA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Niue','NIU');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Norfolk Island','NFK');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Northern Mariana Islands','MNP');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Norway','NOR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Oman','OMN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Pakistan','PAK');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Palau','PLW');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Palestine, State of','PSE');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Panama','PAN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Papua New Guinea','PNG');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Paraguay','PRY');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Peru','PER');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Philippines','PHL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Pitcairn','PCN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Poland','POL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Portugal','PRT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Puerto Rico','PRI');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Qatar','QAT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Romania','ROU');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Russian Federation','RUS');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Rwanda','RWA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Réunion','REU');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Saint Barthélemy','BLM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Saint Helena, Ascension and Tristan da Cunha','SHN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Saint Kitts and Nevis','KNA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Saint Lucia','LCA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Saint Martin (French part)','MAF');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Saint Pierre and Miquelon','SPM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Saint Vincent and the Grenadines','VCT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Samoa','WSM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'San Marino','SMR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Sao Tome and Principe','STP');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Saudi Arabia','SAU');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Senegal','SEN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Serbia','SRB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Seychelles','SYC');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Sierra Leone','SLE');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Singapore','SGP');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Sint Maarten (Dutch part)','SXM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Slovakia','SVK');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Slovenia','SVN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Solomon Islands','SLB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Somalia','SOM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'South Africa','ZAF');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'South Georgia and the South Sandwich Islands','SGS');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'South Sudan','SSD');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Spain','ESP');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Sri Lanka','LKA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Sudan','SDN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Suriname','SUR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Svalbard and Jan Mayen','SJM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Swaziland','SWZ');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Sweden','SWE');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Switzerland','CHE');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Syrian Arab Republic','SYR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Taiwan, Province of China','TWN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Tajikistan','TJK');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Tanzania, United Republic of','TZA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Thailand','THA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Timor-Leste','TLS');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Togo','TGO');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Tokelau','TKL');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Tonga','TON');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Trinidad and Tobago','TTO');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Tunisia','TUN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Turkey','TUR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Turkmenistan','TKM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Turks and Caicos Islands','TCA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Tuvalu','TUV');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Uganda','UGA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Ukraine','UKR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'United Arab Emirates','ARE');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'United Kingdom','GBR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'United States','USA');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'United States Minor Outlying Islands','UMI');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Uruguay','URY');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Uzbekistan','UZB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Vanuatu','VUT');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Venezuela, Bolivarian Republic of','VEN');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Viet Nam','VNM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Virgin Islands, British','VGB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Virgin Islands, U.S.','VIR');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Wallis and Futuna','WLF');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Western Sahara','ESH');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Yemen','YEM');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Zambia','ZMB');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Zimbabwe','ZWE');
INSERT INTO Wild_ID.country(continent_id, name, code) VALUES(1,'Åland Islands','ALA');
