package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * BaitType generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlRootElement
@Entity
@Table(name = "bait_type", catalog = "wild_ID"
)
public class BaitType implements java.io.Serializable {

    @XmlTransient
    private Integer baitTypeId;

    @XmlTransient
    private String name;

    @XmlTransient
    private String description;

    //@XmlTransient
    //private Set deployments = new HashSet(0);
    public BaitType() {
    }

    public BaitType(String name) {
        this.name = name;
    }

    public BaitType(String name, String description) {
        this.name = name;
        this.description = description;
        //this.deployments = deployments;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "bait_type_id", unique = true, nullable = false)
    public Integer getBaitTypeId() {
        return this.baitTypeId;
    }

    public void setBaitTypeId(Integer baitTypeId) {
        this.baitTypeId = baitTypeId;
    }

    @Column(name = "name", nullable = false, length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /*
    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "baitType")
    public Set getDeployments() {
        return this.deployments;
    }

    public void setDeployments(Set deployments) {
        this.deployments = deployments;
    }
     */
}
