package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CameraModelExtendTag generated by hbm2java
 */
@Entity
@Table(name = "camera_model_extend_tag", catalog = "wild_ID"
)
public class CameraModelExtendTag implements java.io.Serializable {

    private Integer cameraModelExtendTagId;
    private CameraModel cameraModel;
    private String name;
    private Set imageExifExtends = new HashSet(0);

    public CameraModelExtendTag() {
    }

    public CameraModelExtendTag(CameraModel cameraModel) {
        this.cameraModel = cameraModel;
    }

    public CameraModelExtendTag(CameraModel cameraModel, String name, Set imageExifExtends) {
        this.cameraModel = cameraModel;
        this.name = name;
        this.imageExifExtends = imageExifExtends;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "camera_model_extend_tag_id", unique = true, nullable = false)
    public Integer getCameraModelExtendTagId() {
        return this.cameraModelExtendTagId;
    }

    public void setCameraModelExtendTagId(Integer cameraModelExtendTagId) {
        this.cameraModelExtendTagId = cameraModelExtendTagId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "camera_model_id", nullable = false)
    public CameraModel getCameraModel() {
        return this.cameraModel;
    }

    public void setCameraModel(CameraModel cameraModel) {
        this.cameraModel = cameraModel;
    }

    @Column(name = "name", length = 64)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cameraModelExtendTag")
    public Set getImageExifExtends() {
        return this.imageExifExtends;
    }

    public void setImageExifExtends(Set imageExifExtends) {
        this.imageExifExtends = imageExifExtends;
    }

}
