package org.wildid.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CameraModelExifFeature generated by hbm2java
 */
@Entity
@Table(name = "camera_model_exif_feature", catalog = "wild_ID"
)
public class CameraModelExifFeature implements java.io.Serializable {

    private Integer cameraModelExifFeatureId;
    private CameraModel cameraModel;
    private ImageFeature imageFeature;
    private String exifTagName;
    private String exifTagValue;
    private String secondaryTagDelimit;
    private String secondaryTagName;

    public CameraModelExifFeature() {
    }

    public CameraModelExifFeature(CameraModel cameraModel, String exifTagName, String secondaryTagDelimit, String secondaryTagName) {
        this.cameraModel = cameraModel;
        this.exifTagName = exifTagName;
        this.secondaryTagDelimit = secondaryTagDelimit;
        this.secondaryTagName = secondaryTagName;
    }

    public CameraModelExifFeature(CameraModel cameraModel, ImageFeature imageFeature, String exifTagName, String secondaryTagDelimit, String secondaryTagName) {
        this.cameraModel = cameraModel;
        this.imageFeature = imageFeature;
        this.exifTagName = exifTagName;
        this.secondaryTagDelimit = secondaryTagDelimit;
        this.secondaryTagName = secondaryTagName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "camera_model_exif_feature_id", unique = true, nullable = false)
    public Integer getCameraModelExifFeatureId() {
        return this.cameraModelExifFeatureId;
    }

    public void setCameraModelExifFeatureId(Integer cameraModelExifFeatureId) {
        this.cameraModelExifFeatureId = cameraModelExifFeatureId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "camera_model_id", nullable = false)
    public CameraModel getCameraModel() {
        return this.cameraModel;
    }

    public void setCameraModel(CameraModel cameraModel) {
        this.cameraModel = cameraModel;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "image_feature_id")
    public ImageFeature getImageFeature() {
        return this.imageFeature;
    }

    public void setImageFeature(ImageFeature imageFeature) {
        this.imageFeature = imageFeature;
    }

    @Column(name = "exif_tag_name", nullable = false, length = 64)
    public String getExifTagName() {
        return this.exifTagName;
    }

    public void setExifTagName(String exifTagName) {
        this.exifTagName = exifTagName;
    }

    @Column(name = "secondary_tag_delimit", nullable = true, length = 1)
    public String getSecondaryTagDelimit() {
        return this.secondaryTagDelimit;
    }

    public void setSecondaryTagDelimit(String secondaryTagDelimit) {
        this.secondaryTagDelimit = secondaryTagDelimit;
    }

    @Column(name = "secondary_tag_name", nullable = true, length = 16)
    public String getSecondaryTagName() {
        return this.secondaryTagName;
    }

    public void setSecondaryTagName(String secondaryTagName) {
        this.secondaryTagName = secondaryTagName;
    }

    @Column(name = "exif_tag_value", nullable = false, length = 256)
    public String getExifTagValue() {
        return exifTagValue;
    }

    public void setExifTagValue(String exifTagValue) {
        this.exifTagValue = exifTagValue;
    }

}
