package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * CameraTrap generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
@Table(name = "camera_trap", catalog = "wild_ID"
)
public class CameraTrap implements java.io.Serializable {

    private Integer cameraTrapId;
    private CameraTrapArray cameraTrapArray;
    private String name;
    private Double latitude;
    private Double longitude;

    @XmlTransient
    private Set<Deployment> deployments = new HashSet<>();

    public CameraTrap() {
    }

    public CameraTrap(CameraTrapArray cameraTrapArray, String name) {
        this.cameraTrapArray = cameraTrapArray;
        this.name = name;
    }

    public CameraTrap(CameraTrapArray cameraTrapArray, String name, Double latitude, Double longitude, Set<Deployment> deployments) {
        this.cameraTrapArray = cameraTrapArray;
        this.name = name;
        this.latitude = latitude;
        this.longitude = longitude;
        this.deployments = deployments;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "camera_trap_id", unique = true, nullable = false)
    public Integer getCameraTrapId() {
        return this.cameraTrapId;
    }

    public void setCameraTrapId(Integer cameraTrapId) {
        this.cameraTrapId = cameraTrapId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "camera_trap_array_id", nullable = false)
    public CameraTrapArray getCameraTrapArray() {
        return this.cameraTrapArray;
    }

    public void setCameraTrapArray(CameraTrapArray cameraTrapArray) {
        this.cameraTrapArray = cameraTrapArray;
    }

    @Column(name = "name", nullable = false, length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "latitude", precision = 22, scale = 0)
    public Double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    @Column(name = "longitude", precision = 22, scale = 0)
    public Double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cameraTrap")
    public Set<Deployment> getDeployments() {
        return this.deployments;
    }

    public void setDeployments(Set<Deployment> deployments) {
        this.deployments = deployments;
    }

}
