package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Continent generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
@Table(name = "continent", catalog = "wild_ID"
)
public class Continent implements java.io.Serializable {

    private Integer continentId;
    private String name;

    @XmlTransient
    private Set countries = new HashSet(0);

    public Continent() {
    }

    public Continent(String name) {
        this.name = name;
    }

    public Continent(String name, Set countries) {
        this.name = name;
        this.countries = countries;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "continent_id", unique = true, nullable = false)
    public Integer getContinentId() {
        return this.continentId;
    }

    public void setContinentId(Integer continentId) {
        this.continentId = continentId;
    }

    @Column(name = "name", nullable = false, length = 32)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "continent")
    public Set getCountries() {
        return this.countries;
    }

    public void setCountries(Set countries) {
        this.countries = countries;
    }

}
