package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Country generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
@Table(name = "country", catalog = "wild_ID"
)
public class Country implements java.io.Serializable {

    private Integer countryId;
    private Continent continent;
    private String name;
    private String code;

    @XmlTransient
    private Set organizations = new HashSet(0);

    @XmlTransient
    private Set projects = new HashSet(0);

    @XmlTransient
    private Set persons = new HashSet(0);

    public Country() {
    }

    public Country(Continent continent, String name, String code) {
        this.continent = continent;
        this.name = name;
        this.code = code;
    }

    public Country(Continent continent, String name, String code, Set organizations, Set projects, Set persons) {
        this.continent = continent;
        this.name = name;
        this.code = code;
        this.organizations = organizations;
        this.projects = projects;
        this.persons = persons;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "country_id", unique = true, nullable = false)
    public Integer getCountryId() {
        return this.countryId;
    }

    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "continent_id", nullable = false)
    public Continent getContinent() {
        return this.continent;
    }

    public void setContinent(Continent continent) {
        this.continent = continent;
    }

    @Column(name = "name", nullable = false, length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "code", nullable = false, length = 4)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
    public Set getOrganizations() {
        return this.organizations;
    }

    public void setOrganizations(Set organizations) {
        this.organizations = organizations;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
    public Set getProjects() {
        return this.projects;
    }

    public void setProjects(Set projects) {
        this.projects = projects;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
    public Set getPersons() {
        return this.persons;
    }

    public void setPersons(Set persons) {
        this.persons = persons;
    }

}
