package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DualDeployment generated by hbm2java
 */
@Entity
@Table(name = "dual_deployment", catalog = "wild_ID"
)
public class DualDeployment implements java.io.Serializable {

    private Integer dualDeploymentId;
    private Deployment deploymentByDeployment2Id;
    private Deployment deploymentByDeployment1Id;

    public DualDeployment() {
    }

    public DualDeployment(Deployment deploymentByDeployment2Id, Deployment deploymentByDeployment1Id) {
        this.deploymentByDeployment2Id = deploymentByDeployment2Id;
        this.deploymentByDeployment1Id = deploymentByDeployment1Id;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "dual_deployment_id", unique = true, nullable = false)
    public Integer getDualDeploymentId() {
        return this.dualDeploymentId;
    }

    public void setDualDeploymentId(Integer dualDeploymentId) {
        this.dualDeploymentId = dualDeploymentId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deployment_2_id", nullable = false)
    public Deployment getDeploymentByDeployment2Id() {
        return this.deploymentByDeployment2Id;
    }

    public void setDeploymentByDeployment2Id(Deployment deploymentByDeployment2Id) {
        this.deploymentByDeployment2Id = deploymentByDeployment2Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deployment_1_id", nullable = false)
    public Deployment getDeploymentByDeployment1Id() {
        return this.deploymentByDeployment1Id;
    }

    public void setDeploymentByDeployment1Id(Deployment deploymentByDeployment1Id) {
        this.deploymentByDeployment1Id = deploymentByDeployment1Id;
    }

}
