package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Event generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
@Table(name = "event", catalog = "wild_ID"
)
public class Event implements java.io.Serializable {

    private Integer eventId;
    private Project project;
    private String name;
    private String description;

    @XmlTransient
    private Set deployments = new HashSet(0);

    public Event() {
    }

    public Event(Project project, String name) {
        this.project = project;
        this.name = name;
    }

    public Event(Project project, String name, String description, Set deployments) {
        this.project = project;
        this.name = name;
        this.description = description;
        this.deployments = deployments;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "event_id", unique = true, nullable = false)
    public Integer getEventId() {
        return this.eventId;
    }

    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "project_id", nullable = false)
    public Project getProject() {
        return this.project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    @Column(name = "name", nullable = false, length = 64)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
    public Set getDeployments() {
        return this.deployments;
    }

    public void setDeployments(Set deployments) {
        this.deployments = deployments;
    }
}
