package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeatureType generated by hbm2java
 */
@Entity
@Table(name = "failure_type", catalog = "wild_ID"
)
public class FailureType implements java.io.Serializable {

    private Integer failureTypeId;
    private String name;

    public FailureType() {
    }

    public FailureType(String name) {
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "failure_type_id", unique = true, nullable = false)
    public Integer getFailureTypeId() {
        return this.failureTypeId;
    }

    public void setFailureTypeId(Integer failureTypeId) {
        this.failureTypeId = failureTypeId;
    }

    @Column(name = "name", nullable = false, length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
