package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * FamilyGenusSpecies generated by hbm2java
 */
//@XmlAccessorType(XmlAccessType.FIELD)
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlRootElement
@Entity
@Table(name = "family_genus_species", catalog = "wild_ID"
)
public class FamilyGenusSpecies implements java.io.Serializable {

    private Integer familyGenusSpeciesId;
    private String class_;
    private String order;
    private String family;
    private String genus;
    private String species;
    private String iucnSpeciesId;
    //private Set imageSpecieses = new HashSet(0);

    @XmlTransient
    private Set<TaxaCommonEnglishName> taxaCommonEnglishNames = new HashSet<>(0);

    public FamilyGenusSpecies() {
    }

    public FamilyGenusSpecies(String class_, String order, String family, String genus, String species, String iucnSpeciesId, Set imageSpecieses) {
        this.class_ = class_;
        this.order = order;
        this.family = family;
        this.genus = genus;
        this.species = species;
        this.iucnSpeciesId = iucnSpeciesId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "family_genus_species_id", unique = true, nullable = false)
    public Integer getFamilyGenusSpeciesId() {
        return this.familyGenusSpeciesId;
    }

    public void setFamilyGenusSpeciesId(Integer familyGenusSpeciesId) {
        this.familyGenusSpeciesId = familyGenusSpeciesId;
    }

    @Column(name = "class", length = 64)
    public String getClass_() {
        return this.class_;
    }

    public void setClass_(String class_) {
        this.class_ = class_;
    }

    @Column(name = "order_taxa", length = 64)
    public String getOrder() {
        return this.order;
    }

    public void setOrder(String order) {
        this.order = order;
    }

    @Column(name = "family", length = 64)
    public String getFamily() {
        return this.family;
    }

    public void setFamily(String family) {
        this.family = family;
    }

    @Column(name = "genus", length = 64)
    public String getGenus() {
        return this.genus;
    }

    public void setGenus(String genus) {
        this.genus = genus;
    }

    @Column(name = "species", length = 64)
    public String getSpecies() {
        return this.species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }

    @Column(name = "iucn_species_id", length = 32)
    public String getIucnSpeciesId() {
        return this.iucnSpeciesId;
    }

    public void setIucnSpeciesId(String iucnSpeciesId) {
        this.iucnSpeciesId = iucnSpeciesId;
    }

    /*
     @OneToMany(fetch = FetchType.LAZY, mappedBy = "familyGenusSpecies")
     public Set getImageSpecieses() {
     return this.imageSpecieses;
     }

     public void setImageSpecieses(Set imageSpecieses) {
     this.imageSpecieses = imageSpecieses;
     }
     */
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "species")
    public Set<TaxaCommonEnglishName> getTaxaCommonEnglishNames() {
        return taxaCommonEnglishNames;
    }

    public void setTaxaCommonEnglishNames(Set<TaxaCommonEnglishName> taxaCommonEnglishNames) {
        this.taxaCommonEnglishNames = taxaCommonEnglishNames;
    }

}
