package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * HomoSapiensType generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
@Table(name = "homo_sapiens_type", catalog = "wild_ID"
)
public class HomoSapiensType implements java.io.Serializable {

    private Integer homoSapiensTypeId;
    private String name;

    @XmlTransient
    private Set imageHomoSapiensTypes = new HashSet(0);

    public HomoSapiensType() {
    }

    public HomoSapiensType(String name) {
        this.name = name;
    }

    public HomoSapiensType(String name, Set imageHomoSapiensTypes) {
        this.name = name;
        this.imageHomoSapiensTypes = imageHomoSapiensTypes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "homo_sapiens_type_id", unique = true, nullable = false)
    public Integer getHomoSapiensTypeId() {
        return this.homoSapiensTypeId;
    }

    public void setHomoSapiensTypeId(Integer homoSapiensTypeId) {
        this.homoSapiensTypeId = homoSapiensTypeId;
    }

    @Column(name = "name", nullable = false, length = 64)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "homoSapiensType")
    public Set getImageHomoSapiensTypes() {
        return this.imageHomoSapiensTypes;
    }

    public void setImageHomoSapiensTypes(Set imageHomoSapiensTypes) {
        this.imageHomoSapiensTypes = imageHomoSapiensTypes;
    }

}
