package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImageExifExtend generated by hbm2java
 */
@Entity
@Table(name = "image_exif_extend", catalog = "wild_ID"
)
public class ImageExifExtend implements java.io.Serializable {

    private Integer imageExifExtendId;
    private CameraModelExtendTag cameraModelExtendTag;
    private Image image;
    private String value;

    public ImageExifExtend() {
    }

    public ImageExifExtend(Image image) {
        this.image = image;
    }

    public ImageExifExtend(CameraModelExtendTag cameraModelExtendTag, Image image, String value) {
        this.cameraModelExtendTag = cameraModelExtendTag;
        this.image = image;
        this.value = value;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "image_exif_extend_id", unique = true, nullable = false)
    public Integer getImageExifExtendId() {
        return this.imageExifExtendId;
    }

    public void setImageExifExtendId(Integer imageExifExtendId) {
        this.imageExifExtendId = imageExifExtendId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "camera_model_extend_tag_id")
    public CameraModelExtendTag getCameraModelExtendTag() {
        return this.cameraModelExtendTag;
    }

    public void setCameraModelExtendTag(CameraModelExtendTag cameraModelExtendTag) {
        this.cameraModelExtendTag = cameraModelExtendTag;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "image_id", nullable = false)
    public Image getImage() {
        return this.image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    @Column(name = "value", length = 256)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
