package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ImageType generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
@Table(name = "image_type", catalog = "wild_ID"
)
public class ImageType implements java.io.Serializable {

    private Integer imageTypeId;
    private String name;

    @XmlTransient
    private Set images = new HashSet(0);

    public ImageType() {
    }

    public ImageType(String name) {
        this.name = name;
    }

    public ImageType(String name, Set images) {
        this.name = name;
        this.images = images;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "image_type_id", unique = true, nullable = false)
    public Integer getImageTypeId() {
        return this.imageTypeId;
    }

    public void setImageTypeId(Integer imageTypeId) {
        this.imageTypeId = imageTypeId;
    }

    @Column(name = "name", nullable = false, length = 32)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "imageSequence")
    public Set getImages() {
        return this.images;
    }

    public void setImages(Set images) {
        this.images = images;
    }

}
