package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ImageExif generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
@Table(name = "image_exif", catalog = "wild_ID"
)
public class ImageExif implements java.io.Serializable {

    private Integer imageExifId;

    @XmlTransient
    private Image image;

    private ImageFeature imageFeature;
    private String exifTagValue;

    public ImageExif() {
    }

    public ImageExif(Image image) {
        this.image = image;
    }

    public ImageExif(Image image, ImageFeature imageFeature, String exifTagValue) {
        this.image = image;
        this.imageFeature = imageFeature;
        this.exifTagValue = exifTagValue;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "image_exif_id", unique = true, nullable = false)
    public Integer getImageExifId() {
        return this.imageExifId;
    }

    public void setImageExifId(Integer imageExifId) {
        this.imageExifId = imageExifId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "image_id", nullable = false)
    public Image getImage() {
        return this.image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "image_feature_id", nullable = false)
    public ImageFeature getImageFeature() {
        return this.imageFeature;
    }

    public void setImageFeature(ImageFeature imageFeature) {
        this.imageFeature = imageFeature;
    }

    @Column(name = "exif_tag_value", length = 256)
    public String getExifTagValue() {
        return this.exifTagValue;
    }

    public void setExifTagValue(String exifTagValue) {
        this.exifTagValue = exifTagValue;
    }

}
