package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectOrganizationId generated by hbm2java
 */
@Embeddable
public class ProjectOrganizationId implements java.io.Serializable {

    private int projectId;
    private int organizationId;

    public ProjectOrganizationId() {
    }

    public ProjectOrganizationId(int projectId, int organizationId) {
        this.projectId = projectId;
        this.organizationId = organizationId;
    }

    @Column(name = "project_id", nullable = false)
    public int getProjectId() {
        return this.projectId;
    }

    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    @Column(name = "organization_id", nullable = false)
    public int getOrganizationId() {
        return this.organizationId;
    }

    public void setOrganizationId(int organizationId) {
        this.organizationId = organizationId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ProjectOrganizationId)) {
            return false;
        }
        ProjectOrganizationId castOther = (ProjectOrganizationId) other;

        return (this.getProjectId() == castOther.getProjectId())
                && (this.getOrganizationId() == castOther.getOrganizationId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getProjectId();
        result = 37 * result + this.getOrganizationId();
        return result;
    }

}
