package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ProjectStatus generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
@Table(name = "project_status", catalog = "wild_ID"
)
public class ProjectStatus implements java.io.Serializable {

    private int projectStatusId;
    private String status;

    @XmlTransient
    private Set projects = new HashSet(0);

    public ProjectStatus() {
    }

    public ProjectStatus(int projectStatusId) {
        this.projectStatusId = projectStatusId;
    }

    public ProjectStatus(int projectStatusId, String status) {
        this.projectStatusId = projectStatusId;
        this.status = status;
    }

    public ProjectStatus(int projectStatusId, String status, Set projects) {
        this.projectStatusId = projectStatusId;
        this.status = status;
        this.projects = projects;
    }

    @Id
    @Column(name = "project_status_id", unique = true, nullable = false)
    public int getProjectStatusId() {
        return this.projectStatusId;
    }

    public void setProjectStatusId(int projectStatusId) {
        this.projectStatusId = projectStatusId;
    }

    @Column(name = "status", length = 128)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "projectStatus")
    public Set getProjects() {
        return this.projects;
    }

    public void setProjects(Set projects) {
        this.projects = projects;
    }

}
