package org.wildid.entity;
// Generated Sep 16, 2015 3:35:06 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ProjectOrganization generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
@Table(name = "project_organization", catalog = "wild_ID"
)
public class ProjectOrganization implements java.io.Serializable {

    private ProjectOrganizationId id;
    private Organization organization;

    @XmlTransient
    private Project project;

    public ProjectOrganization() {
    }

    public ProjectOrganization(ProjectOrganizationId id, Organization organization, Project project) {
        this.id = id;
        this.organization = organization;
        this.project = project;
    }

    public ProjectOrganization(Organization organization, Project project) {
        this.id = new ProjectOrganizationId(project.getProjectId().intValue(),
                organization.getOrganizationId().intValue());
        this.organization = organization;
        this.project = project;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "projectId", column = @Column(name = "project_id", nullable = false)),
        @AttributeOverride(name = "organizationId", column = @Column(name = "organization_id", nullable = false))})
    public ProjectOrganizationId getId() {
        return this.id;
    }

    public void setId(ProjectOrganizationId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "organization_id", nullable = false, insertable = false, updatable = false)
    public Organization getOrganization() {
        return this.organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id", nullable = false, insertable = false, updatable = false)
    public Project getProject() {
        return this.project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

}
